# Generated by Django 5.1 on 2024-09-08 02:01

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Prediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to=core.models.get_upload_path)),
                (
                    "user_result",
                    models.ImageField(
                        blank=True, null=True, upload_to=core.models.get_upload_path
                    ),
                ),
                (
                    "model_result",
                    models.ImageField(
                        blank=True, null=True, upload_to=core.models.get_upload_path
                    ),
                ),
                (
                    "rgb_image",
                    models.ImageField(
                        blank=True, null=True, upload_to=core.models.get_upload_path
                    ),
                ),
                ("temperature", models.FloatField()),
                ("humidity", models.FloatField()),
                ("precipitation", models.FloatField()),
                ("wind_speed", models.FloatField()),
                ("wind_direction", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Ожидание"), ("complete", "Завершено")],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Предсказание",
                "verbose_name_plural": "Предсказания",
            },
        ),
    ]
